# Generated by Django 6.0.6 on 2026-06-29 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produto', models.CharField(choices=[('TECIDO', 'Tecido'), ('PAPEL', 'Papel'), ('TINTA', 'Tinta'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Material')),
                ('quantidade_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantidade Base (Metros ou Litros)')),
                ('metros_por_rolo', models.DecimalField(blank=True, decimal_places=2, help_text='Se vendido em rolo, quantos metros tem um rolo padrão?', max_digits=8, null=True)),
                ('tipo_tinta', models.CharField(choices=[('SUBLIMACAO', 'Sublimação'), ('SOLVENTE', 'Solvente'), ('N/A', 'Não se aplica')], default='N/A', max_length=20)),
                ('cor_tinta', models.CharField(choices=[('CYAN', 'Cyan'), ('MAGENTA', 'Magenta'), ('YELLOW', 'Yellow'), ('BLACK', 'Black (Preto)'), ('LIGHT_CYAN', 'Light Cyan'), ('LIGHT_MAGENTA', 'Light Magenta'), ('BRANCO', 'Branco'), ('INCOLOR', 'Incolor/N/A')], default='INCOLOR', max_length=20)),
                ('litros_por_vidro', models.DecimalField(blank=True, decimal_places=2, help_text='Quantos litros vem em um vidro/garrafa padrão?', max_digits=6, null=True)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produto')),
            ],
        ),
    ]
