# Generated by Django 6.0.6 on 2026-06-30 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_ordemcompra_itemordemcompra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR', 'Criação'), ('EDITAR', 'Edição'), ('EXCLUIR', 'Exclusão'), ('ENTRADA', 'Entrada Estoque'), ('SAIDA', 'Saída Estoque'), ('APROVAR', 'Aprovação'), ('CANCELAR', 'Cancelamento'), ('RECEBER', 'Recebimento')], max_length=20)),
                ('descricao', models.CharField(max_length=500)),
                ('modelo', models.CharField(blank=True, default='', max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
