# Generated by Django 6.0.6 on 2026-07-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_criar_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(choices=[('TECIDO', 'Tecido'), ('PAPEL', 'Papel'), ('TINTA', 'Tinta'), ('AVIAMENTO', 'Aviamento'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
    ]
