# Generated by Django 6.0.6 on 2026-07-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_add_categoria_and_expand_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade (un)'), ('M', 'Metros (m)'), ('KG', 'Quilogramas (kg)'), ('L', 'Litros (L)'), ('RL', 'Rolo (rl)'), ('CX', 'Caixa (cx)'), ('PC', 'Peça (pc)'), ('G', 'Gramas (g)'), ('ML', 'Mililitros (ml)'), ('OUTRO', 'Outro')], default='UN', max_length=10, verbose_name='Unidade de Medida'),
        ),
    ]
