# Generated by Django 6.0.6 on 2026-07-28 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_alter_itemfechamento_preco_custo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoNFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_cod_nota_ent', models.BigIntegerField(help_text='Corresponde ao campo nCodNotaEnt retornado pela API do Omie.', unique=True, verbose_name='ID da Nota no Omie')),
                ('cod_int_nota_ent', models.CharField(blank=True, default='', max_length=60, verbose_name='Código de Integração')),
                ('numero_nfe', models.CharField(blank=True, default='', max_length=20, verbose_name='Número NF-e')),
                ('fornecedor_nome', models.CharField(blank=True, default='', max_length=200, verbose_name='Fornecedor')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Importação')),
                ('observacao', models.CharField(blank=True, default='', max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Importação de NF-e',
                'verbose_name_plural': 'Importações de NF-e',
                'ordering': ['-data_importacao'],
            },
        ),
    ]
