# Generated by Django 6.0.6 on 2026-08-22 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_fechamento_por_periodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='movimentacao_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['ENTRADA', 'SAIDA'])), name='movimentacao_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_base__gte', 0)), name='produto_quantidade_base_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('preco_custo__isnull', True), ('preco_custo__gte', 0), _connector='OR'), name='produto_preco_custo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('preco_venda__isnull', True), ('preco_venda__gte', 0), _connector='OR'), name='produto_preco_venda_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_minimo__isnull', True), ('estoque_minimo__gte', 0), _connector='OR'), name='produto_estoque_minimo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('metros_por_rolo__isnull', True), ('metros_por_rolo__gt', 0), _connector='OR'), name='produto_metros_rolo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('litros_por_vidro__isnull', True), ('litros_por_vidro__gt', 0), _connector='OR'), name='produto_litros_vidro_positivo'),
        ),
    ]
