# Generated by Django 6.0.6 on 2026-08-22 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_normalizar_perfis_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logacao',
            index=models.Index(fields=['-data'], name='logacao_data_idx'),
        ),
        migrations.AddIndex(
            model_name='logacao',
            index=models.Index(fields=['acao', '-data'], name='logacao_acao_data_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['-data'], name='movimentacao_data_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['tipo', '-data'], name='movimentacao_tipo_data_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['tipo_produto', 'descricao'], name='produto_tipo_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['quantidade_base', 'estoque_minimo'], name='produto_saldo_min_idx'),
        ),
    ]
