# Generated by Django 6.0.6 on 2026-08-22 23:38

import estoque.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0018_logacao_logacao_data_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoomie',
            name='app_secret',
            field=estoque.fields.EncryptedCharField(blank=True, default='', max_length=255, verbose_name='App Secret Omie'),
        ),
    ]
