# Generated by Django 6.0.6 on 2026-08-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_criptografar_segredos_omie_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='motivo',
            field=models.CharField(blank=True, choices=[('PRODUCAO', 'Uso em Produção / Consumo'), ('AVARIA', 'Avaria / Defeito / Perda'), ('VENCIMENTO', 'Vencimento / Descarte'), ('AJUSTE', 'Ajuste de Inventário'), ('COMPRA', 'Compra / Reposição'), ('DEVOLUCAO', 'Devolução'), ('OUTRO', 'Outro')], default='', max_length=20, verbose_name='Motivo'),
        ),
    ]
