# Generated by Django 6.0.6 on 2026-07-08 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0011_movimentacao_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OmieConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Configuração principal', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('app_key', models.CharField(max_length=100)),
                ('app_secret_encrypted', models.TextField(blank=True, default='')),
                ('ambiente', models.CharField(choices=[('PRODUCAO', 'Produção'), ('HOMOLOGACAO', 'Homologação')], default='PRODUCAO', max_length=20)),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Omie',
                'verbose_name_plural': 'Configurações Omie',
            },
        ),
        migrations.CreateModel(
            name='OmieNotaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omie_codigo_nota', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('omie_codigo_integracao', models.CharField(blank=True, max_length=100, null=True)),
                ('chave_nfe', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Chave NF-e')),
                ('numero_nf', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número NF')),
                ('serie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Série')),
                ('fornecedor_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome Fornecedor (Nota)')),
                ('fornecedor_cnpj', models.CharField(blank=True, max_length=30, verbose_name='CNPJ Fornecedor (Nota)')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('IMPORTADA', 'Importada'), ('IGNORADA', 'Ignorada'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=20)),
                ('raw_json', models.JSONField(blank=True, default=dict, verbose_name='JSON Bruto')),
                ('erro', models.TextField(blank=True, default='', verbose_name='Log de Erro')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fornecedor', verbose_name='Fornecedor Vinculado')),
            ],
            options={
                'verbose_name': 'Nota de Entrada Omie',
                'verbose_name_plural': 'Notas de Entrada Omie',
                'ordering': ['-data_emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OmieNotaEntradaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField(default=1)),
                ('codigo_produto_omie', models.CharField(blank=True, max_length=100, verbose_name='Cód. Produto Omie')),
                ('codigo_produto_fornecedor', models.CharField(blank=True, max_length=100, verbose_name='Cód. Prod. Fornecedor')),
                ('descricao', models.TextField(verbose_name='Descrição do Item')),
                ('ncm', models.CharField(blank=True, max_length=20, verbose_name='NCM')),
                ('cfop', models.CharField(blank=True, max_length=20, verbose_name='CFOP')),
                ('unidade_nota', models.CharField(blank=True, max_length=20, verbose_name='Unidade Nota')),
                ('quantidade_nota', models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Qtd. Nota')),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Val. Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Val. Total')),
                ('quantidade_convertida', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Qtd. Convertida')),
                ('unidade_convertida', models.CharField(blank=True, max_length=20, verbose_name='Unidade Convertida')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VINCULADO', 'Vinculado'), ('IGNORADO', 'Ignorado'), ('IMPORTADO', 'Importado'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=20)),
                ('raw_json', models.JSONField(blank=True, default=dict, verbose_name='JSON Item Bruto')),
                ('erro', models.TextField(blank=True, default='', verbose_name='Log de Erro Item')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.movimentacao', verbose_name='Movimentação Estoque')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='omie.omienotaentrada')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto', verbose_name='Produto Interno')),
            ],
            options={
                'verbose_name': 'Item da Nota de Entrada',
                'verbose_name_plural': 'Itens da Nota de Entrada',
                'ordering': ['sequencia'],
            },
        ),
        migrations.CreateModel(
            name='OmieProdutoMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_cnpj', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='CNPJ Fornecedor')),
                ('codigo_produto_omie', models.CharField(blank=True, max_length=100, verbose_name='Cód. Produto Omie')),
                ('codigo_produto_fornecedor', models.CharField(blank=True, max_length=100, verbose_name='Cód. Prod. Fornecedor')),
                ('descricao_fornecedor', models.TextField(blank=True, verbose_name='Descrição do Fornecedor')),
                ('unidade_nota', models.CharField(blank=True, max_length=20, verbose_name='Unidade Nota')),
                ('fator_conversao_para_base', models.DecimalField(decimal_places=6, default=1.0, help_text='Multiplicador para converter a unidade da nota para a unidade base do produto. Ex: se a nota vem em caixas de 50 metros, e a base é Metros, o fator é 50.', max_digits=14, verbose_name='Fator de Conversão')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto', verbose_name='Produto Interno')),
            ],
            options={
                'verbose_name': 'Mapeamento de Produto Omie',
                'verbose_name_plural': 'Mapeamentos de Produtos Omie',
                'unique_together': {('fornecedor_cnpj', 'codigo_produto_omie', 'codigo_produto_fornecedor')},
            },
        ),
    ]
