# Generated by Django 6.0.6 on 2026-07-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='omienotaentrada',
            name='codigo_omie_fornecedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Fornecedor Omie'),
        ),
        migrations.AddField(
            model_name='omienotaentrada',
            name='valor_mercadorias',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Valor Mercadorias'),
        ),
        migrations.AddField(
            model_name='omienotaentradaitem',
            name='codigo_local_estoque_omie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cód. Local Estoque Omie'),
        ),
        migrations.AddField(
            model_name='omienotaentradaitem',
            name='codigo_omie_item',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código Item Omie'),
        ),
        migrations.AddField(
            model_name='omienotaentradaitem',
            name='codigo_omie_produto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código Produto Omie'),
        ),
    ]
