# Generated by Django 6.0.6 on 2026-07-09 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_movimentacao_usuario'),
        ('omie', '0002_omienotaentrada_codigo_omie_fornecedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OmieRecebimentoNFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recebimento_omie', models.BigIntegerField(help_text='nIdReceb da Omie', unique=True, verbose_name='ID Recebimento Omie')),
                ('chave_nfe', models.CharField(help_text='cChaveNFe da Omie', max_length=60, unique=True, verbose_name='Chave NF-e')),
                ('modelo', models.CharField(help_text='cModeloNFe. Ex: 55 ou 57', max_length=5, verbose_name='Modelo')),
                ('numero_nf', models.CharField(blank=True, max_length=30, verbose_name='Número NF')),
                ('serie', models.CharField(blank=True, max_length=20, verbose_name='Série')),
                ('etapa', models.CharField(blank=True, max_length=50, verbose_name='Etapa')),
                ('fornecedor_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome Fornecedor (Nota)')),
                ('fornecedor_cnpj', models.CharField(blank=True, max_length=30, verbose_name='CNPJ Fornecedor (Nota)')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_registro', models.DateField(blank=True, null=True, verbose_name='Data de Registro')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('IMPORTADA', 'Importada'), ('IGNORADA', 'Ignorada'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=20)),
                ('raw_header', models.JSONField(blank=True, default=dict, verbose_name='JSON Header')),
                ('raw_detalhado', models.JSONField(blank=True, default=dict, verbose_name='JSON Detalhado (Itens)')),
                ('erro', models.TextField(blank=True, default='', verbose_name='Log de Erro')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fornecedor', verbose_name='Fornecedor Vinculado')),
            ],
            options={
                'verbose_name': 'Recebimento NF-e Omie',
                'verbose_name_plural': 'Recebimentos NF-e Omie',
                'ordering': ['-data_emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OmieRecebimentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField(default=1)),
                ('id_item_omie', models.BigIntegerField(blank=True, null=True, verbose_name='ID Item Omie')),
                ('id_produto_omie', models.BigIntegerField(blank=True, null=True, verbose_name='ID Produto Omie')),
                ('codigo_produto', models.CharField(blank=True, max_length=100, verbose_name='Cód. Produto')),
                ('descricao', models.TextField(verbose_name='Descrição do Item')),
                ('ncm', models.CharField(blank=True, max_length=20, verbose_name='NCM')),
                ('cfop_nfe', models.CharField(blank=True, max_length=20, verbose_name='CFOP NF-e')),
                ('cfop_entrada', models.CharField(blank=True, max_length=20, verbose_name='CFOP Entrada')),
                ('unidade_entrada', models.CharField(blank=True, max_length=20, verbose_name='Unidade Entrada')),
                ('quantidade_entrada', models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Qtd. Entrada')),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Val. Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Val. Total')),
                ('quantidade_convertida', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Qtd. Convertida')),
                ('unidade_convertida', models.CharField(blank=True, max_length=20, verbose_name='Unidade Convertida')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VINCULADO', 'Vinculado'), ('IGNORADO', 'Ignorado'), ('IMPORTADO', 'Importado'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=20)),
                ('erro', models.TextField(blank=True, default='', verbose_name='Log de Erro Item')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.movimentacao', verbose_name='Movimentação Estoque')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto', verbose_name='Produto Interno')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='omie.omierecebimentonfe')),
            ],
            options={
                'verbose_name': 'Item Recebimento NF-e',
                'verbose_name_plural': 'Itens Recebimento NF-e',
                'ordering': ['sequencia'],
            },
        ),
    ]
