# Generated by Django 6.0.6 on 2026-09-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('event_id', models.UUIDField()),
                ('severity', models.CharField(max_length=50)),
                ('audience', models.CharField(max_length=100)),
                ('sucesso', models.BooleanField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'log de notificação',
                'verbose_name_plural': 'logs de notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('audience_key', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'destinatário de notificação',
                'verbose_name_plural': 'destinatários de notificações',
                'ordering': ['nome'],
            },
        ),
    ]
